# Generated by Ansible role raspberry_cm5_nixos — do not edit on target
{ config, lib, pkgs, ... }:

{
  services.essensys.gateway.eth0Mac = "88:a2:9e:34:27:61";
  services.essensys.gateway.eth1Mac = "00:e0:4c:68:01:be";
  services.essensys.gateway.eth1Address = "10.0.1.1";
  services.essensys.gateway.eth1Prefix = 24;
  services.essensys.gateway.eth0Address = "192.168.0.14";
  services.essensys.gateway.armoireHostname = "mon.essensys.fr";
  services.essensys.nvme.device = "/dev/disk/by-label/essensys-data";
}
